global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'your-email@example.com'
  smtp_auth_password: 'your-app-password'
  smtp_require_tls: true

  # Slack webhook URL (optional)
  slack_api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'

# The root route on which each incoming alert enters.
route:
  # Group alerts by these labels
  group_by: ['alertname', 'cluster', 'service']
  
  # Wait before sending initial notification
  group_wait: 10s
  
  # Wait before sending notification about new alerts in the same group
  group_interval: 10s
  
  # Wait before resending notifications
  repeat_interval: 1h
  
  # Default receiver
  receiver: 'default-receiver'
  
  # Child routes
  routes:
    # Critical alerts go to PagerDuty and Slack
    - match:
        severity: critical
      receiver: 'critical-receiver'
      continue: true
      
    # Warning alerts only go to Slack
    - match:
        severity: warning
      receiver: 'warning-receiver'

# Inhibition rules to mute certain notifications
inhibit_rules:
  # Inhibit warning alerts if there's already a critical alert for the same service
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service']

# Receivers configuration
receivers:
  # Default receiver (console output for development)
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true

  # Critical alerts receiver
  - name: 'critical-receiver'
    email_configs:
      - to: 'oncall@example.com'
        headers:
          Subject: '[CRITICAL] {{ .GroupLabels.alertname }} - {{ .GroupLabels.service }}'
    slack_configs:
      - channel: '#alerts-critical'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true
    # Uncomment for PagerDuty integration
    # pagerduty_configs:
    #   - service_key: 'YOUR-PAGERDUTY-SERVICE-KEY'

  # Warning alerts receiver
  - name: 'warning-receiver'
    slack_configs:
      - channel: '#alerts-warning'
        title: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        send_resolved: true